package main

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	_ "github.com/lib/pq"
)

var titles = []string{
	"The Hunger Games (The Hunger Games, #1)",
	"Harry Potter and the Order of the Phoenix",
	"Pride and Prejudice",
	"To Kill a Mockingbird",
	"The Book Thief",
	"Twilight (The Twilight Saga, #1)",
	"Animal Farm",
	"J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings",
	"The Chronicles of Narnia (The Chronicles of Narnia, #1-7)",
	"The Fault in Our Stars",
	"The Picture of Dorian Gray",
	"Gone with the Wind",
	"The Giving Tree",
	"Wuthering Heights",
	"The Perks of Being a Wallflower",
	"Jane Eyre",
	"Harry Potter and the Sorcerer's Stone (Harry Potter, #1)",
	"The Great Gatsby",
	"The Lightning Thief (Percy Jackson and the Olympians, #1)",
	"The Little Prince",
	"The Da Vinci Code (Robert Langdon, #2)",
	"Alice's Adventures in Wonderland / Through the Looking-Glass",
	"Memoirs of a Geisha",
	"Crime and Punishment",
	"Divergent (Divergent, #1)",
	"Les Misérables",
	"Lord of the Flies",
	"Romeo and Juliet",
	"Anne of Green Gables (Anne of Green Gables, #1)",
	"City of Bones (The Mortal Instruments, #1)",
	"The Help",
	"Ender’s Game (Ender's Saga, #1)",
	"Dracula",
	"Charlotte's Web",
	"Of Mice and Men",
	"The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy, #1)",
	"The Alchemist",
	"The Catcher in the Rye",
	"Fahrenheit 451",
	"Brave New World",
	"One Hundred Years of Solitude",
	"A Thousand Splendid Suns",
	"The Time Traveler's Wife",
	"The Princess Bride",
	"The Secret Garden",
	"A Game of Thrones (A Song of Ice and Fire, #1)",
	"The Outsiders",
	"A Wrinkle in Time (Time Quintet, #1)",
	"Little Women",
	"1984",
	"The Odyssey",
	"The Kite Runner",
	"Frankenstein: The 1818 Text",
	"Harry Potter and the Deathly Hallows (Harry Potter, #7)",
	"The Lovely Bones",
	"The Adventures of Huckleberry Finn",
	"Where the Wild Things Are",
	"The Giver (The Giver, #1)",
	"The Handmaid’s Tale (The Handmaid's Tale, #1)",
	"Green Eggs and Ham",
	"Life of Pi",
	"A Tale of Two Cities",
	"Lolita",
	"Dune (Dune, #1)",
	"Slaughterhouse-Five",
	"Water for Elephants",
	"Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)",
	"The Bell Jar",
	"Matilda",
	"The Stand",
	"Catch-22",
	"The Pillars of the Earth (Kingsbridge, #1)",
	"The Adventures of Sherlock Holmes (Sherlock Holmes, #3)",
	"Watership Down (Watership Down, #1)",
	"Rebecca",
	"Great Expectations",
	"Outlander (Outlander, #1)",
	"The Girl with the Dragon Tattoo (Millennium, #1)",
	"The Color Purple",
	"The Fellowship of the Ring (The Lord of the Rings, #1)",
	"One Flew Over the Cuckoo's Nest",
	"My Sister's Keeper",
	"Anna Karenina",
	"The Brothers Karamazov",
	"A Tree Grows in Brooklyn",
	"A Clockwork Orange",
	"The Road",
	"And Then There Were None",
	"The Golden Compass (His Dark Materials, #1)",
	"Vampire Academy (Vampire Academy, #1)",
	"To Kill a Mockingbird",
	"Angela's Ashes (Frank McCourt, #1)",
	"Siddhartha",
	"It",
	"The Shining (The Shining, #1)",
	"The Complete Stories and Poems",
	"Don Quixote",
	"Interview with the Vampire (The Vampire Chronicles, #1)",
	"The Poisonwood Bible",
	"The Old Man and the Sea",
	"Atlas Shrugged",
	"Harry Potter and the Goblet of Fire (Harry Potter, #4)",
	"The Notebook (The Notebook, #1)",
	"Winnie-the-Pooh (Winnie-the-Pooh #1)",
	"Fahrenheit 451",
	"Harry Potter and the Half-Blood Prince (Harry Potter #6)",
	"Moby-Dick or, The Whale",
	"A Prayer for Owen Meany",
	"Clockwork Angel (The Infernal Devices, #1)",
	"The Stranger",
	"The Secret Life of Bees",
	"The Red Tent",
	"Harry Potter and the Chamber of Secrets (Harry Potter, #2)",
	"The Name of the Wind (The Kingkiller Chronicle, #1)",
	"The Master and Margarita",
	"The Metamorphosis",
	"Middlesex",
	"The Hobbit (The Lord of the Rings, #0)",
	"Eragon (The Inheritance Cycle, #1)",
	"The Adventures of Tom Sawyer",
	"Looking for Alaska",
	"The Alchemist",
	"Charlie and the Chocolate Factory (Charlie Bucket, #1)",
	"The Very Hungry Caterpillar",
	"The Curious Incident of the Dog in the Night-Time",
	"The Count of Monte Cristo",
	"The Last Olympian (Percy Jackson and the Olympians, #5)",
	"The Shadow of the Wind (The Cemetery of Forgotten Books, #1)",
	"Tuesdays with Morrie",
	"The Lion, the Witch and the Wardrobe (Chronicles of Narnia, #1)",
	"The Unbearable Lightness of Being",
	"On the Road",
	"The Name of the Rose",
	"The Godfather (The Godfather, #1)",
	"Where the Red Fern Grows",
	"In Cold Blood",
	"Holes (Holes, #1)",
	"The Scarlet Letter",
	"Perfume: The Story of a Murderer",
	"Fight Club",
	"The Five People You Meet in Heaven",
	"American Gods",
	"The Cat in the Hat (The Cat in the Hat, #1)",
	"The Divine Comedy",
	"Watchmen",
	"Hush, Hush (Hush, Hush, #1)",
	"All Quiet on the Western Front",
	"The Little House Collection (Little House, #1-9)",
	"Lonesome Dove (Lonesome Dove, #1)",
	"Peter Pan",
	"Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch",
	"The Addiction Manifesto",
	"Six of Crows (Six of Crows, #1)",
	"Love in the Time of Cholera",
	"Insurgent (Divergent, #2)",
	"A Walk to Remember",
	"The Thorn Birds",
	"The Compleat Works of Wllm Shkspr",
	"The Battle of the Labyrinth (Percy Jackson and the Olympians, #4)",
	"Shadow Kiss (Vampire Academy, #3)",
	"The Ultimate Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy, #1-5)",
	"How the Grinch Stole Christmas!",
	"The Titan's Curse (Percy Jackson and the Olympians, #3)",
	"Clockwork Princess (The Infernal Devices, #3)",
	"Their Eyes Were Watching God",
	"The Importance of Being Earnest",
	"The Sea of Monsters (Percy Jackson and the Olympians, #2)",
	"Atonement",
	"Eat, Pray, Love",
	"The Wonderful Wizard of Oz (Oz, #1)",
	"The Three Musketeers",
	"The Lorax",
	"Goodnight Moon",
	"The Maze Runner (The Maze Runner, #1)",
	"Catching Fire (The Hunger Games, #2)",
	"A Midsummer Night's Dream",
	"Frostbite (Vampire Academy, #2)",
	"The Haunting of Hill House",
	"Tess of the D'Urbervilles",
	"The Hunger Games Trilogy Boxset (The Hunger Games, #1-3)",
	"Heart of Darkness",
	"Blood Promise (Vampire Academy, #4)",
	"Throne of Glass (Throne of Glass, #1)",
	"The Prophet",
	"Bridge to Terabithia",
	"Murder on the Orient Express (Hercule Poirot, #10)",
	"The Good Earth (House of Earth, #1)",
	"The Call of the Wild",
	"The Secret History",
	"The Joy Luck Club",
	"Alice in Wonderland",
	"The Phantom Tollbooth",
	"The Silence of the Lambs  (Hannibal Lecter, #2)",
	"Oh, the Places You'll Go!",
	"Madame Bovary",
	"The Mists of Avalon (Avalon, #1)",
	"The Neverending Story",
	"The Night Circus",
	"Oliver Twist",
	"The Selection (The Selection, #1)",
	"Treasure Island",
	"Jonathan Livingston Seagull",
	"A Story of Yesterday",
	"The Song of Achilles",
	"The Girl Who Played with Fire (Millennium, #2)",
	"Ulysses",
	"A Storm of Swords (A Song of Ice and Fire, #3)",
	"Fifty Shades of Grey (Fifty Shades, #1)",
	"A Court of Mist and Fury (A Court of Thorns and Roses, #2)",
	"The Boy in the Striped Pajamas",
	"The Diary of a Young Girl",
	"The Clan of the Cave Bear (Earth's Children, #1)",
	"Jurassic Park (Jurassic Park, #1)",
	"Beloved",
	"A Farewell to Arms",
	"Misery",
	"The Canterbury Tales",
	"David Copperfield",
	"The World According to Garp",
	"Thirteen Reasons Why",
	"A Little Princess",
	"The Lost Hero (The Heroes of Olympus, #1)",
	"His Dark Materials (His Dark Materials #1-3)",
	"The Chain Between Worlds (The Lost Artefacts #1)",
	"Wicked: The Life and Times of the Wicked Witch of the West (The Wicked Years, #1)",
	"Schindler's List",
	"Shōgun",
	"The Green Mile",
	"Clockwork Prince (The Infernal Devices, #2)",
	"The Silmarillion",
	"Extremely Loud & Incredibly Close",
	"The Velveteen Rabbit",
	"The Trial",
	"The Iliad / The Odyssey",
	"Cinder (The Lunar Chronicles, #1)",
	"The Other Boleyn Girl (The Plantagenet and Tudor Novels, #9)",
	"The Hitchhiker's Guide to the Galaxy (The Hitchhiker's Guide to the Galaxy, #1)",
	"Fallen (Fallen, #1)",
	"Last Sacrifice (Vampire Academy, #6)",
	"A Confederacy of Dunces",
	"The Sun Also Rises",
	"Man's Search for Meaning",
	"The Secret Magdalene",
	"Gone Girl",
	"The Crucible: A Play in Four Acts",
	"The Seven Husbands of Evelyn Hugo",
	"City of Fallen Angels (The Mortal Instruments, #4)",
	"Cat's Cradle",
	"The Screwtape Letters",
	"A Light in the Attic",
	"The Wind in the Willows",
	"Spirit Bound (Vampire Academy, #5)",
	"The God of Small Things",
	"The Phantom of the Opera",
	"The Hiding Place: The Triumphant True Story of Corrie Ten Boom",
	"Blindness",
	"Girl with a Pearl Earring",
	"Ella Enchanted (Ella Enchanted, #1)",
	"A Clash of Kings  (A Song of Ice and Fire, #2)",
	"Uglies (Uglies, #1)",
	"The Wind-Up Bird Chronicle",
	"Marley and Me: Life and Love With the World's Worst Dog",
	"She's Come Undone",
	"Shiver (The Wolves of Mercy Falls, #1)",
	"The Guernsey Literary and Potato Peel Pie Society",
	"The House of the Spirits",
	"Fear and Loathing in Las Vegas",
	"The Shack",
	"The Sound and the Fury",
	"Norwegian Wood",
	"Speak",
	"For Whom the Bell Tolls",
	"The Complete Calvin and Hobbes",
	"The Lord of the Rings",
	"Mockingjay (The Hunger Games, #3)",
	"Island of the Blue Dolphins",
	"Marked (House of Night, #1)",
	"Roots: The Saga of an American Family",
	"Stranger in a Strange Land",
	"Paper Towns",
	"Kafka on the Shore",
	"Othello",
	"The Girl Who Kicked the Hornet's Nest (Millennium, #3)",
	"Into the Wild",
	"Inkheart (Inkworld, #1)",
	"The Complete Sherlock Holmes",
	"The Idiot",
	"Neverwhere (London Below, #1)",
	"King Lear",
	"Beautiful Disaster (Beautiful, #1)",
	"Blood River: A Journey to Africa's Broken Heart",
	"Delirium (Delirium, #1)",
	"The Things They Carried",
	"White Oleander",
	"The Vampire Lestat (The Vampire Chronicles, #2)",
	"Uncle Tom's Cabin",
	"Crooked Kingdom (Six of Crows, #2)",
	"The Way of Kings (The Stormlight Archive, #1)",
	"Invisible Man",
	"Different Seasons",
	"The Once and Future King (The Once and Future King, #1-4)",
	"Midnight Sun [2008 Draft]",
	"All Creatures Great and Small (All Creatures Great and Small, #1-2)",
	"I Know This Much Is True",
	"Foundation (Foundation, #1)",
	"Never Let Me Go",
	"Flow Down Like Silver",
	"Candide",
	"James and the Giant Peach",
	"Paradise Lost",
	"The Historian",
	"Ready Player One (Ready Player One, #1)",
	"The Time Machine",
	"Lamb: The Gospel According to Biff, Christ's Childhood Pal",
	"The Complete Works",
	"The Thirteenth Tale",
	"Heidi",
	"Wonder (Wonder, #1)",
	"Leaves of Grass",
	"City of Lost Souls (The Mortal Instruments, #5)",
	"The Son of Neptune (The Heroes of Olympus, #2)",
	"The Wise Man's Fear (The Kingkiller Chronicle, #2)",
	"Graceling (Graceling Realm, #1)",
	"The Cider House Rules",
	"The Mark of Athena (The Heroes of Olympus, #3)",
	"Shatter Me (Shatter Me, #1)",
	"Me Before You (Me Before You, #1)",
	"Are You There God? It's Me, Margaret",
	"Fangirl",
	"The Final Empire (Mistborn, #1)",
	"'Salem's Lot",
	"Walden",
	"Sophie's World",
	"The Martian",
	"Mrs. Dalloway",
	"East of Eden",
	"The Awakening",
	"Legend (Legend, #1)",
	"Fried Green Tomatoes at the Whistle Stop Cafe (Whistle Stop #1)",
	"The Complete Maus",
	"Sophie's Choice",
	"The Hound of the Baskervilles (Sherlock Holmes, #5)",
	"Hamlet",
	"Fifty Shades Darker (Fifty Shades, #2)",
	"The Prince of Tides",
	"A Court of Thorns and Roses (A Court of Thorns and Roses, #1)",
	"Middlemarch",
	"Stardust",
	"Dead Until Dark (Sookie Stackhouse, #1)",
	"Do Androids Dream of Electric Sheep?",
	"Things Fall Apart (The African Trilogy, #1)",
	"Eleanor & Park",
	"The Monster at the End of this Book",
	"A Time to Kill (Jake Brigance, #1)",
	"Bridget Jones's Diary (Bridget Jones, #1)",
	"All the Light We Cannot See",
	"Black Beauty",
	"The Magician's Nephew (Chronicles of Narnia, #6)",
	"Number the Stars",
	"The Graveyard Book",
	"Franny and Zooey",
	"V for Vendetta",
	"The Witches",
	"Aristotle and Dante Discover the Secrets of the Universe (Aristotle and Dante, #1)",
	"The Art of Racing in the Rain",
	"A Short History of Nearly Everything",
	"The Power of One (The Power of One, #1)",
	"Love You Forever",
	"If I Stay (If I Stay, #1)",
	"The Gunslinger (The Dark Tower, #1)",
	"White Fang",
	"American Psycho",
	"Beowulf",
	"Allegiant (Divergent, #3)",
	"The Complete Novels",
	"Gulliver's Travels",
	"Harry Potter Series Box Set (Harry Potter, #1-7)",
	"A Portrait of the Artist as a Young Man",
	"Tuck Everlasting",
	"The Eye of the World (The Wheel of Time, #1)",
	"Fifty Shades Freed (Fifty Shades, #3)",
	"Bel Canto",
	`A Child Called "It" (Dave Pelzer, #1)`,
	"Cold Mountain",
	"The Tell-Tale Heart and Other Writings",
	"Go Ask Alice",
	"Dark Lover (Black Dagger Brotherhood, #1)",
	"As I Lay Dying",
	"The Martian Chronicles",
	"Eldest (The Inheritance Cycle, #2)",
	"Cloud Atlas",
	"11/22/63",
	"It Ends with Us (It Ends with Us, #1)",
	"War and Peace",
	"Beautiful Creatures (Caster Chronicles, #1)",
	"A Separate Peace",
	"Mansfield Park",
	"Dr. Jekyll and Mr. Hyde",
	"Tao Te Ching",
	"Steppenwolf",
	"The Hunchback of Notre-Dame",
	"Brisingr (The Inheritance Cycle, #3)",
	"Inferno",
	"Obsidian (Lux, #1)",
	"The Grapes of Wrath",
	"The House of Hades (The Heroes of Olympus, #4)",
	"The BFG",
	"زندگی مه آلود پریا",
	"The Amazing Adventures of Kavalier & Clay",
	"Robinson Crusoe",
	"The Cruel Prince (The Folk of the Air, #1)",
	"Stargirl (Stargirl, #1)",
	"Room",
	"Zen and the Art of Motorcycle Maintenance: An Inquiry Into Values (Phaedrus, #1)",
	"The Last Song",
	"The Amber Spyglass (His Dark Materials, #3)",
	"Dear John",
	"City of Heavenly Fire (The Mortal Instruments, #6)",
	"Midnight's Children",
	"Doctor Zhivago",
	"The English Patient",
	"The Firm",
	"Heir of Fire (Throne of Glass #3)",
	"Crescendo (Hush, Hush, #2)",
	"The Plague",
	"Like Water for Chocolate",
	"The Remains of the Day",
	"My Ántonia (Great Plains Trilogy, #3)",
	"Dragonfly in Amber (Outlander, #2)",
	"Miss Peregrine's Home for Peculiar Children (Miss Peregrine's Peculiar Children, #1)",
	"Flowers in the Attic (Dollanganger, #1)",
	"Breakfast of Champions",
	"Midnight in the Garden of Good and Evil",
	"Breakfast at Tiffany's and Three Stories",
	"Ignite Me (Shatter Me, #3)",
	"The Origin of Species",
	"The Subtle Knife (His Dark Materials, #2)",
	"A Streetcar Named Desire",
	"Hopeless (Hopeless, #1)",
	"A Fine Balance",
	"Daughter of Smoke & Bone (Daughter of Smoke & Bone, #1)",
	"The Prince",
	"Death of a Salesman",
	"Infinite Jest",
	"Coraline",
	"Red Queen (Red Queen, #1)",
	"The One (The Selection, #3)",
	"Crown of Midnight (Throne of Glass, #2)",
	"Blood Meridian, or, the Evening Redness in the West",
	"A Little Life",
	"Unbroken: A World War II Story of Survival, Resilience and Redemption",
	"All the Bright Places",
	"Evermore (The Immortals, #1)",
	"A Feast for Crows (A Song of Ice and Fire, #4)",
	"The Virgin Suicides",
	"Pippi Longstocking (Pippi Långstrump, #1)",
	"Snow Flower and the Secret Fan",
	"The Scarlet Pimpernel",
	"Carrie",
	"Jonathan Strange & Mr Norrell",
	"Matched (Matched, #1)",
	"The Angel Experiment (Maximum Ride, #1)",
	"Anna and the French Kiss (Anna and the French Kiss, #1)",
	"The Host (The Host, #1)",
	"Artemis Fowl (Artemis Fowl, #1)",
	"I Know Why the Caged Bird Sings (Maya Angelou's Autobiography, #1)",
	"Faust, First Part",
	"High Fidelity",
	"The Shipping News",
	"The Chosen (Reuven Malther, #1)",
	"The Tales of Beedle the Bard (Hogwarts Library, #3)",
	"The Devil in the White City: Murder, Magic, and Madness at the Fair That Changed America",
	"Pet Sematary",
	"Waiting for Godot",
	"Houdini Heart",
	"Northanger Abbey",
	"Shantaram",
	"Nineteen Minutes",
	"We Were Liars",
	"I, Robot (Robot, #0.1)",
	"Neuromancer (Sprawl, #1)",
	"To the Lighthouse",
	"The Reader",
	"Redeeming Love",
	"The Voyage of the Dawn Treader (Chronicles of Narnia, #3)",
	"The Lost Symbol (Robert Langdon, #3)",
	"Persuasion",
	"The Age of Innocence",
	"Where the Crawdads Sing",
	"Queen of Shadows (Throne of Glass #4)",
	"Dubliners",
	"The Exorcist",
	"The Waste Land",
	"A Dance with Dragons (A Song of Ice and Fire, #5)",
	"Lover Awakened (Black Dagger Brotherhood, #3)",
	"The Return of the King (The Lord of the Rings, #3)",
	"The Hate U Give (The Hate U Give, #1)",
	"The Pearl",
	"Betrayed (House of Night, #2)",
	"Divine Secrets of the Ya-Ya Sisterhood",
	"Circe",
	"The Republic",
	"The Jungle",
	"The Twilight Collection",
	"Red, White & Royal Blue",
	"City of Glass (The Mortal Instruments, #3)",
	"Voyager (Outlander, #3)",
	"Me Talk Pretty One Day",
	"The Goldfinch",
	"The Last Battle (Chronicles of Narnia, #7)",
	"Untamed (House of Night, #4)",
	"Everything is Illuminated",
	"I, Claudius (Claudius, #1)",
	"A Christmas Carol",
	"Snow Falling on Cedars",
	"The 5th Wave (The 5th Wave, #1)",
	"A Room with a View",
	"Angels & Demons (Robert Langdon, #1)",
	"A Good Girl's Guide to Murder (A Good Girl's Guide to Murder, #1)",
	"Bleak House",
	"The Fellowship of the Ring (The Lord of the Rings, #1)",
	"The Elite (The Selection, #2)",
	"Chosen (House of Night, #3)",
	"Night  (The Night Trilogy, #1)",
	"The Complete Poems of Emily Dickinson",
	"The Raven Boys (The Raven Cycle, #1)",
	"The Invisible Life of Addie LaRue",
	"The Nightingale",
	"Emma",
	"The War of the Worlds",
	"A Discovery of Witches (All Souls, #1)",
	"Of Human Bondage",
	"North and South",
	"The Elephant Tree",
	"The God Delusion",
	"Brideshead Revisited",
	"The Bad Beginning (A Series of Unfortunate Events, #1)",
	"Ugly Love",
	"The Two Towers (The Lord of the Rings, #2)",
	"World War Z: An Oral History of the Zombie War",
	"Bloodlines (Bloodlines, #1)",
	"The Woman in White",
	"The Iron King (The Iron Fey, #1)",
	"A Court of Wings and Ruin (A Court of Thorns and Roses, #3)",
	"Sense and Sensibility",
	"The Witching Hour (Lives of the Mayfair Witches, #1)",
	"Unwind (Unwind, #1)",
	"Wizard's First Rule (Sword of Truth, #1)",
	"Snow Crash",
	"2001: A Space Odyssey",
	"Johnny Got His Gun",
	"Vanity Fair",
	"Cry, the Beloved Country",
	"Bared to You (Crossfire, #1)",
	"Torment (Fallen, #2)",
	"Cannery Row (Cannery Row, #1)",
	"Far From the Madding Crowd",
	"Are You My Mother?",
	"The Polar Express",
	"A Great and Terrible Beauty (Gemma Doyle, #1)",
	"Sarah's Key",
	"The Mortal Instruments Boxed Set: City of Bones; C…hes; City of Glass (The Mortal Instruments, #1-3)",
	"The Left Hand of Darkness",
	"Shadow and Bone (The Shadow and Bone Trilogy, #1)",
	"Chocolat (Chocolat, #1)",
	"A Monster Calls",
	"Much Ado About Nothing",
	"Into Thin Air: A Personal Account of the Mount Everest Disaster",
	"Little House on the Prairie (Little House, #3)",
	"Halfway to the Grave (Night Huntress, #1)",
	"The Summoning (Darkest Powers, #1)",
	"Perfect Chemistry (Perfect Chemistry, #1)",
	"Just Listen",
	"Three Cups of Tea: One Man's Mission to Promote Peace ... One School at a Time",
	"The Red Pyramid (The Kane Chronicles, #1)",
	"The Darkest Minds (The Darkest Minds, #1)",
	"Angelfall (Penryn & the End of Days, #1)",
	"The Last Lecture",
	"Silence (Hush, Hush, #3)",
	"The Horse and His Boy (Chronicles of Narnia, #5)",
	"Cutting for Stone",
	"Ishmael (Ishmael, #1)",
	"Hyperion (Hyperion Cantos, #1)",
	"Twelfth Night",
	"The Truth About Forever",
	"Du côté de chez Swann (À la recherche du temps perdu, #1)",
	"Macbeth",
	"Sabriel (Abhorsen,  #1)",
	"Trainspotting (Mark Renton, #2)",
	"I'll Give You the Sun",
	"Anne of Avonlea (Anne of Green Gables, #2)",
	"Little House in the Big Woods (Little House, #1)",
	"Nine Stories",
	"The Unbecoming of Mara Dyer (Mara Dyer, #1)",
	"Lady Chatterley's Lover",
	"I Am Number Four (Lorien Legacies, #1)",
	"Words of Radiance (The Stormlight Archive, #2)",
	"The Westing Game",
	"Dead to the World (Sookie Stackhouse, #4)",
	"The Goose Girl (The Books of Bayern, #1)",
	"Cress (The Lunar Chronicles, #3)",
	"No Country for Old Men",
	"Acheron (Dark-Hunter, #14)",
	"The Hours",
	"I Capture the Castle",
	"The Bronze Horseman (The Bronze Horseman, #1)",
	"You Are Special (Wemmicksville, #1)",
	"The Glass Menagerie",
	"Empire of Storms (Throne of Glass, #5)",
	"Julius Caesar",
	"Slammed (Slammed, #1)",
	"Demian. Die Geschichte von Emil Sinclairs Jugend",
	"The Zombie Room",
	"Drums of Autumn (Outlander, #4)",
	"Speaker for the Dead (Ender's Saga, #2)",
	"The Art of War",
	"The Last Unicorn (The Last Unicorn, #1)",
	"P.S. I Love You (P.S. I Love You, #1)",
	"Cyrano de Bergerac",
	"We Need to Talk About Kevin",
	"Scarlet (The Lunar Chronicles, #2)",
	"The Arabian Nights",
	"World Without End (Kingsbridge, #2)",
	"Call Me By Your Name (Call Me By Your Name, #1)",
	"Interpreter of Maladies",
	"Hunted (House of Night, #5)",
	"The Talisman (The Talisman, #1)",
	"The Bean Trees (Greer Family, #1)",
	"The Silver Chair (Chronicles of Narnia, #4)",
	"Wicked Lovely (Wicked Lovely, #1)",
	"A Dog's Purpose (A Dog's Purpose, #1)",
	"A Wizard of Earthsea (Earthsea Cycle, #1)",
	"Sapiens: A Brief History of Humankind",
	"The Knife of Never Letting Go (Chaos Walking, #1)",
	"Before I Fall",
	"All the King's Men",
	"Lover Eternal (Black Dagger Brotherhood, #2)",
	"A Brief History of Time",
	"Invisible Monsters",
	"The Merchant of Venice",
	"The Inheritance Games (The Inheritance Games, #1)",
	"The Secret (The Secret, #1)",
	"One Day in the Life of Ivan Denisovich",
	"Gravity's Rainbow",
	"Inheritance (The Inheritance Cycle, #4)",
	"The Lies of Locke Lamora (Gentleman Bastard, #1)",
	"The Yellow Wallpaper and Other Stories",
	"Unravel Me (Shatter Me, #2)",
	"The Queen of the Damned (The Vampire Chronicles, #3)",
	"Inferno (Robert Langdon, #4)",
	"Carry On (Simon Snow, #1)",
	"Peace Like a River",
	"Prince Caspian (Chronicles of Narnia, #2)",
	"1Q84 (1Q84, #1-3)",
	"The Eyre Affair (Thursday Next, #1)",
	"The Scorch Trials (The Maze Runner, #2)",
	"I Am Legend and Other Stories",
	"Into the Wild (Warriors, #1)",
	"The Girl on the Train",
	"Poison Study (Study, #1)",
	"Foucault's Pendulum",
	"Oryx and Crake (MaddAddam, #1)",
	"The Wicked King (The Folk of the Air, #2)",
	"City of Ashes (The Mortal Instruments, #2)",
	"Mythology",
	"Seabiscuit: An American Legend",
	"The Memory Keeper's Daughter",
	"Oedipus Rex  (The Theban Plays, #1)",
	"Where She Went (If I Stay, #2)",
	"The Glass Castle",
	"House of Leaves",
	"Left Behind (Left Behind, #1)",
	"A People's History of the United States",
	"Native Son",
	"The Bourne Identity (Jason Bourne, #1)",
	"The History of Love",
	"To All the Boys I've Loved Before (To All the Boys I've Loved Before, #1)",
	"The Night Before Christmas",
	"Something Wicked This Way Comes",
	"They Both Die at the End",
	"The Bluest Eye",
	"Daisy Jones & The Six",
	"If on a Winter's Night a Traveler",
	"Darkfever (Fever, #1)",
	"We Have Always Lived in the Castle",
	"The Killer Angels (The Civil War Trilogy, #2)",
	"Rosencrantz and Guildenstern Are Dead",
	"Twenty Thousand Leagues Under the Sea (Captain Nemo, #2)",
	"Champion (Legend, #3)",
	"The Magus",
	"The Ocean at the End of the Lane",
	"Shadowfever (Fever, #5)",
	"Dandelion Wine",
	"Gone (Gone, #1)",
	"The Long Walk",
	"The Silent Patient",
	"Battle Royale",
	"The Wasp Factory",
	"Dome: Rebellion (Dome, #1)",
	"Night Watch (Discworld, #29; City Watch, #6)",
	"On Writing: A Memoir of the Craft",
	"Miracle",
	"Assassin's Apprentice (Farseer Trilogy, #1)",
	"John Adams",
	"Alanna: The First Adventure (Song of the Lioness, #1)",
	"Watchers",
	"The Fiery Cross (Outlander, #5)",
	"The Holy Bible: King James Version",
	"The Queen of Nothing (The Folk of the Air, #3)",
	"Simon vs. the Homo Sapiens Agenda (Simonverse, #1)",
	"House of Sand and Fog",
	"Possession",
	"Of Monsters And Planes",
	"The Blind Assassin",
	"Pretties (Uglies, #2)",
	"Lover Unbound (Black Dagger Brotherhood, #5)",
	"Papillon",
	"Red Rising (Red Rising Saga, #1)",
	"A Man Called Ove",
	"One for the Money (Stephanie Plum, #1)",
	"A Breath of Snow and Ashes (Outlander, #6)",
	"Mistress Suffragette",
	"Heartstopper: Volume One (Heartstopper, #1)",
	"The Dark Tower (The Dark Tower, #7)",
	"From the Mixed-Up Files of Mrs. Basil E. Frankweiler",
	"Veronika Decides to Die",
	"Grimm's Fairy Tales",
	"Geek Love",
	"Odd Thomas (Odd Thomas, #1)",
	"Freakonomics: A Rogue Economist Explores the Hidden Side of Everything",
	"The Sirens of Titan",
	"The Love Hypothesis",
	"Death on the Nile (Hercule Poirot, #18)",
	"Cosmos",
	"The Blood of Olympus (The Heroes of Olympus, #5)",
	"Corelli's Mandolin",
	"The Sisterhood of the Traveling Pants (Sisterhood, #1)",
	"Prodigal Summer",
	"Jitterbug Perfume",
	"The Trigger: Hunting the Assassin Who Brought the World to War",
	"A Heartbreaking Work of Staggering Genius",
	"Verity",
	"Under the Dome",
	"Bury My Heart at Wounded Knee: An Indian History of the American West",
	"The Death Cure (The Maze Runner, #3)",
	"The Witch of Blackbird Pond",
	"Tempted (House of Night, #6)",
	"Prodigy (Legend, #2)",
	"The Book of Mormon: Another Testament of Jesus Christ",
	"The Elegance of the Hedgehog",
	"The Alienist (Dr. Laszlo Kreizler, #1)",
	"I'd Tell You I Love You, But Then I'd Have to Kill You (Gallagher Girls, #1)",
	"Anthem",
	"Howl and Other Poems",
	"The No. 1 Ladies' Detective Agency (No. 1 Ladies' Detective Agency, #1)",
	"Sharp Objects",
	"The Iliad",
	"The Hero of Ages (Mistborn, #3)",
	"How to Win Friends and Influence People",
	"Message in a Bottle",
	"Ivanhoe",
	"Love Story (Love Story, #1)",
	"It's Kind of a Funny Story",
	"The Big Sleep (Philip Marlowe, #1)",
	"A Canticle for Leibowitz (St. Leibowitz, #1)",
	"Rubinrot (Edelstein-Trilogie, #1)",
	"The Aeneid",
	"Walk Two Moons",
	"One Fish, Two Fish, Red Fish, Blue Fish",
	"The Murder of Roger Ackroyd (Hercule Poirot, #4)",
	"Ender's Shadow (The Shadow Series, #1)",
	"The Story of My Life",
	"The Corrections",
	"The Magic Mountain",
	"Angle of Repose",
	"Club Dead (Sookie Stackhouse, #3)",
	"Princess Academy (Princess Academy, #1)",
	"Confessions of a Shopaholic (Shopaholic, #1)",
	"Lover Revealed (Black Dagger Brotherhood, #4)",
	"Song of Solomon",
	"The Shell Seekers",
	"Digital Fortress",
	"The Invention of Hugo Cabret",
	"The Color of Magic (Discworld, #1; Rincewind, #1)",
	"Hard-Boiled Wonderland and the End of the World",
	"Living Dead in Dallas (Sookie Stackhouse, #2)",
	"One Day",
	"The Jungle Books",
	"The Power of Myth",
	"The Eden Paradox (Eden Paradox, #1)",
	"The Edge of Never (The Edge of Never, #1)",
	"Antigone (The Theban Plays, #3)",
	"Glass Houses (The Morganville Vampires, #1)",
	"Tales of Old: Greek Mythology: Volume 1",
	"Kingdom of Ash (Throne of Glass, #7)",
	"Lover Avenged (Black Dagger Brotherhood, #7)",
	"Because of Winn-Dixie",
	"Around the World in Eighty Days",
	"Ficciones",
	"An Ember in the Ashes (An Ember in the Ashes, #1)",
	"Small Gods (Discworld, #13)",
	"Chasing the Devil: The Search for Africa's Fighting Spirit",
	"Cryptonomicon (Crypto, #1)",
	"The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change",
	"Jude the Obscure",
	"The Omnivore's Dilemma: A Natural History of Four Meals",
	"Naked Lunch",
	"Still Alice",
	"My Name Is Asher Lev",
	"The Portrait of a Lady",
	"Normal People",
	"Worm Holes (Quantum Roots, #2)",
	"Mort (Discworld, #4; Death, #1)",
	"Fire (Graceling Realm, #2)",
	"Howards End",
	"Choke",
	"Educated",
	"The Moon Is a Harsh Mistress",
	"An Abundance of Katherines",
	"Mary Poppins (Mary Poppins, #1)",
	"Starship Troopers",
	"Swan Song",
	"One of Us Is Lying (One of Us is Lying, #1)",
	"The Namesake",
	"Orlando",
	"The Passage (The Passage, #1)",
	"The Agony and the Ecstasy",
	"Holy Bible: New International Version",
	"A Darker Shade of Magic (Shades of Magic, #1)",
	"Archer's Voice",
	"Shutter Island",
	"Caraval (Caraval, #1)",
	"Wild Swans: Three Daughters of China",
	"Meditations",
	"Let the Right One In",
	"Finale (Hush, Hush, #4)",
	"Mystic River",
	"Linger (The Wolves of Mercy Falls, #2)",
	"Tender Is the Night",
	"Pale Fire",
	"Survivor",
	"I Am the Messenger",
	"The Sea of Tranquility",
	"The Forgotten Garden",
	"A Court of Mist and Fury (A Court of Thorns and Roses, #2)",
	"Exodus",
	"The Bridges of Madison County",
	"Ethan Frome",
	"House of Earth and Blood (Crescent City, #1)",
	"The Restaurant at the End of the Universe (Hitchhiker's Guide to the Galaxy, #2)",
	"Walking Disaster (Beautiful, #2)",
	"The Assassin's Blade (Throne of Glass, #0.1-0.5)",
	"Daughter of the Forest  (Sevenwaters, #1)",
	"Forrest Gump (Forrest Gump, #1)",
	"Illusions: The Adventures of a Reluctant Messiah",
	"Gift from the Sea",
	"The Hunt for Red October (Jack Ryan, #3)",
	"The Awakening (Darkest Powers, #2)",
	"Revolutionary Road",
	"Cold Sassy Tree",
	"84, Charing Cross Road",
	"Nausea",
	"Absalom, Absalom!",
	"The Hotel New Hampshire",
	"Tai-Pan (Asian Saga, #2)",
	"The Millennium Trilogy (Millennium Trilogy, #1-3)",
	"The Fall",
	"The Reckoning (Darkest Powers, #3)",
	"Dreamfever (Fever, #4)",
	"Kane & Abel (Kane & Abel, #1)",
	"Fablehaven (Fablehaven, #1)",
	"The Sparrow (The Sparrow, #1)",
	"Winter (The Lunar Chronicles, #4)",
	"A Walk in the Woods: Rediscovering America on the Appalachian Trail",
	"The House in the Cerulean Sea (The House in the Cerulean Sea, #1)",
	"Specials (Uglies, #3)",
	"Dark Places",
	"Gabriel's Inferno (Gabriel's Inferno, #1)",
	"The Well of Ascension (Mistborn, #2)",
	"Shakespeare's Sonnets",
	"Reflected in You (Crossfire, #2)",
	"Dead as a Doornail (Sookie Stackhouse, #5)",
	"The Sorrows of Young Werther",
	"A Study in Scarlet (Sherlock Holmes, #1)",
	"Where the Heart Is",
	"The Gargoyle",
	"The 5 Love Languages: The Secret to Love that Lasts",
	"We",
	"A Million Little Pieces",
	"Guilty Pleasures (Anita Blake, Vampire Hunter, #1)",
	"Definitely Dead (Sookie Stackhouse, #6)",
	"A Moveable Feast",
	"One Foot in the Grave (Night Huntress, #2)",
	"A Connecticut Yankee in King Arthur's Court",
	"The Pact",
	"The City of Ember (Book of Ember, #1)",
	"The Golden Lily (Bloodlines, #2)",
	"Christy",
	"Lover Mine (Black Dagger Brotherhood, #8)",
	"Journey to the End of the Night",
	"If We Were Villains",
	"The Bonfire of the Vanities",
	"Opal (Lux, #3)",
	"Crank (Crank, #1)",
	"The Runaway Jury",
	"Burned (House of Night, #7)",
	"Childhood's End",
	"The Fountainhead",
	"The Story of Edgar Sawtelle",
	"Deception Point",
	"Pandemonium (Delirium, #2)",
	"Keeper of the Lost Cities",
	"Between Shades of Gray",
	"Still Life with Woodpecker",
	"The Lucky One",
	"Beach Music",
	"Stoner",
	"Valley of the Dolls",
	"Night World, No. 1 (Night World, #1-3)",
	"Safe Haven",
	"The Amulet of Samarkand (Bartimaeus, #1)",
	"Onyx (Lux, #2)",
	"Sometimes a Great Notion",
	"The Brief Wondrous Life of Oscar Wao",
	"How Green Was My Valley",
	"Easy (Contours of the Heart, #1)",
	"Turtles All the Way Down",
	"The Poetry of Robert Frost",
	"The Turn of the Screw",
	"The House of Mirth",
	"The Wedding (The Notebook, #2)",
	"From Dead to Worse (Sookie Stackhouse, #8)",
	"Scythe (Arc of a Scythe, #1)",
	"Lady Midnight (The Dark Artifices, #1)",
	"Thoughtless (Thoughtless, #1)",
	"On the Beach",
	"Beauty: A Retelling of the Story of Beauty and the Beast",
	"Will Grayson, Will Grayson",
	"The Dead Zone",
	"Wizard and Glass (The Dark Tower, #4)",
	"Becoming",
	"The Complete Persepolis",
	"Fourth Wing (The Empyrean, #1)",
	"All Together Dead (Sookie Stackhouse, #7)",
	"Thus Spoke Zarathustra",
	"Roll of Thunder, Hear My Cry (Logans, #4)",
	"Passion (Fallen, #3)",
	"Dead and Gone (Sookie Stackhouse, #9)",
	"This Lullaby",
	"The Bhagavad Gita",
	"The Ruins of Gorlan (Ranger's Apprentice, #1)",
	"The Mysterious Benedict Society (The Mysterious Benedict Society, #1)",
	"Light in August",
	"Hatchet (Brian's Saga, #1)",
	"The Monarch's Ring (The Lost Artefacts, #2)",
	"The Dispossessed: An Ambiguous Utopia",
	"White Noise",
	"The Immortal Life of Henrietta Lacks",
	"Bitten (Otherworld, #1)",
	"Animal Farm / 1984",
	"Redwall (Redwall, #1)",
	"Isabella Warrior Queen",
	"Breaking Dawn (The Twilight Saga, #4)",
	"Faefever (Fever, #3)",
	"Helter Skelter: The True Story of the Manson Murders",
	"Why They Stay: Sex Scandals, Deals, and Hidden Agendas of Eight Political Wives",
	"Disgrace",
	"Silas Marner",
	"The Rime of the Ancient Mariner",
	"The Midnight Library",
	"Tiger's Curse (The Tiger Saga, #1)",
	"God Is the Cure, Love Is the Answer: A Memoir",
	"Fantasy Lover (Hunter Legends, #1)",
	"Wings (Wings, #1)",
	"The Awakening / The Struggle (The Vampire Diaries, #1-2)",
	"The Story of Ferdinand",
	"Heartless",
	"The Drawing of the Three (The Dark Tower, #2)",
	"Death Leaves a Shadow (Marlowe Black Mystery, #2)",
	"The Taming of the Shrew",
	"All the Pretty Horses (The Border Trilogy, #1)",
	"The Maltese Falcon",
	"These Is My Words: The Diary of Sarah Agnes Prine,…1901, Arizona Territories (Sarah Agnes Prine, #1)",
	"The Far Pavilions",
	"The Horse Whisperer",
	"Red Dragon (Hannibal Lecter, #1)",
	"Every Day (Every Day, #1)",
	"The Guardian",
	"Hogfather (Discworld, #20; Death, #4)",
	"Everything, Everything",
	"Requiem for a Dream",
	"The Collector",
	"A Doll's House",
}

type GoogleBooksResponse struct {
	Items []struct {
		VolumeInfo VolumeInfo `json:"volumeInfo"`
		Id         string     `json:"id"`
	} `json:"items"`
}

type VolumeInfo struct {
	Title         string     `json:"title"`
	Authors       []string   `json:"authors"`
	Publisher     string     `json:"publisher"`
	PublishedDate string     `json:"publishedDate"`
	Categories    []string   `json:"categories"`
	ImageLinks    ImageLinks `json:"imageLinks"`
}

type ImageLinks struct {
	SmallThumbnail string `json:"smallThumbnail"`
	Thumbnail      string `json:"thumbnail"`
}

func main() {
	psqlInfo := "***REMOVED***"
	db, err := sql.Open("postgres", psqlInfo)
	if err != nil {
		fmt.Println("Error connecting to database: ", err)
		return
	}
	defer db.Close()

	apiKey := "your-api-key-here"

	// Construct the request URL

	for _, title := range titles {
		baseUrl := "https://www.googleapis.com/books/v1/volumes"
		query := url.Values{}
		query.Add("key", apiKey)
		query.Add("q", "intitle:"+title)
		urlString := baseUrl + "?" + query.Encode()

		fmt.Println("processing: ", title)
		fmt.Println("processing: ", urlString)
		time.Sleep(1 * time.Second)
		resp, err := http.Get(urlString)
		if err != nil {
			fmt.Printf("Error making request: %s\n", err)
			return
		}
		defer resp.Body.Close()

		// Read the response body
		body, err := io.ReadAll(resp.Body)
		if err != nil {
			fmt.Printf("Error reading response body: %s\n", err)
			return
		}

		// Unmarshal the JSON response
		var response GoogleBooksResponse
		err = json.Unmarshal(body, &response)
		if err != nil {
			fmt.Println("Error unmarshaling: ", err)
			return
		}

		if len(response.Items) == 0 {
			_, _ = db.Exec("INSERT INTO notFound (title) VALUES ($1)", title)
			fmt.Println("No results found")
			continue
		}

		book := response.Items[0]
		authors := strings.Join(book.VolumeInfo.Authors, ", ")
		categories := strings.Join(book.VolumeInfo.Categories, ", ")

		_, err = db.Exec("INSERT INTO books (title, authors, publisher, published_date, categories, thumbnail) VALUES ($1, $2, $3, $4, $5, $6)",
			book.VolumeInfo.Title,
			authors,
			book.VolumeInfo.Publisher,
			book.VolumeInfo.PublishedDate,
			categories,
			book.VolumeInfo.ImageLinks.Thumbnail,
		)

		if err != nil {
			_, err = db.Exec("INSERT INTO bookserror (bookId) VALUES ($1)", book.Id)
			fmt.Println("Error inserting record: ", err)
			continue
		}

		fmt.Println("Record inserted successfully")
	}
}
